import type { ITitreRestau } from './TitreRestaurantTable'

export const data: ITitreRestau[] = [
  {
    id: '1',
    annee: 2024,
    mois: 'Août',
    nbr_jr: 19,
    note: 'Titre attribué après validation de la présence.',
  },
  {
    id: '2',
    annee: 2023,
    mois: 'Septembre',
    nbr_jr: 21,
    note: 'Nombre de jours travaillé bien confirmé.',
  },
  {
    id: '3',
    annee: 2023,
    mois: 'Novembre',
    nbr_jr: 20,
    note: 'Données vérifiées par le service RH interne.',
  },
  {
    id: '4',
    annee: 2023,
    mois: 'Octobre',
    nbr_jr: 22,
    note: 'Aucune absence non justifiée n’est signalée.',
  },
  {
    id: '5',
    annee: 2023,
    mois: 'Août',
    nbr_jr: 18,
    note: 'Congés validés en début de mois concerné.',
  },
  {
    id: '6',
    annee: 2023,
    mois: 'Juillet',
    nbr_jr: 20,
    note: 'Le salarié a effectué tous ses jours.',
  },
  {
    id: '7',
    annee: 2023,
    mois: 'Décembre',
    nbr_jr: 19,
    note: 'Période marquée par des congés partiels déclarés.',
  },
  {
    id: '8',
    annee: 2023,
    mois: 'Juin',
    nbr_jr: 22,
    note: 'Présence totale sans aucun jour d’absence noté.',
  },
  {
    id: '9',
    annee: 2023,
    mois: 'Mai',
    nbr_jr: 21,
    note: 'Absence partielle justifiée par arrêt maladie court.',
  },
  {
    id: '10',
    annee: 2023,
    mois: 'Avril',
    nbr_jr: 20,
    note: 'Aucun incident signalé pendant cette période travaillée.',
  },
  {
    id: '11',
    annee: 2023,
    mois: 'Mars',
    nbr_jr: 21,
    note: 'Données saisies automatiquement par le logiciel interne.',
  },
  {
    id: '12',
    annee: 2023,
    mois: 'Février',
    nbr_jr: 19,
    note: 'Présence confirmée via les feuilles de pointage RH.',
  },
  {
    id: '13',
    annee: 2022,
    mois: 'Décembre',
    nbr_jr: 20,
    note: 'Congés de fin d’année pris en compte également.',
  },
  {
    id: '14',
    annee: 2022,
    mois: 'Novembre',
    nbr_jr: 21,
    note: 'Participation complète aux journées obligatoires notée.',
  },
  {
    id: '15',
    annee: 2022,
    mois: 'Octobre',
    nbr_jr: 22,
    note: 'Tous les jours travaillés ont été validés manuellement.',
  },
  {
    id: '16',
    annee: 2022,
    mois: 'Septembre',
    nbr_jr: 20,
    note: 'Aucune anomalie détectée dans le relevé du mois.',
  },
  {
    id: '17',
    annee: 2022,
    mois: 'Août',
    nbr_jr: 18,
    note: 'Plusieurs jours fériés ont impacté le nombre total.',
  },
  {
    id: '18',
    annee: 2022,
    mois: 'Juillet',
    nbr_jr: 20,
    note: 'L’activité a été normale tout au long du mois.',
  },
  {
    id: '19',
    annee: 2022,
    mois: 'Juin',
    nbr_jr: 21,
    note: 'Les justificatifs d’absence ont bien été déposés.',
  },
  {
    id: '20',
    annee: 2022,
    mois: 'Mai',
    nbr_jr: 22,
    note: 'Aucune absence injustifiée enregistrée durant ce mois.',
  },
]
