import type { ITitreRestau } from './TitreRestaurantTable'

export const data: ITitreRestau[] = [
  {
    id: '1',
    salarie: {
      nom: 'Durand',
      prenom: 'Alice',
      email: 'alice.durand@finanssor.fr',
    },
    annee: 2024,
    mois: 'Août',
    nbr_jr: 19,
    note: 'Titre attribué après validation de la présence.',
  },
  {
    id: '2',
    salarie: {
      nom: 'Martin',
      prenom: 'Jean',
      email: 'jean.martin@finanssor.fr',
    },
    annee: 2023,
    mois: 'Septembre',
    nbr_jr: 21,
    note: 'Nombre de jours travaillé bien confirmé.',
  },
  {
    id: '3',
    salarie: {
      nom: 'Nguyen',
      prenom: 'Linh',
      email: 'linh.nguyen@finanssor.fr',
    },
    annee: 2023,
    mois: 'Novembre',
    nbr_jr: 20,
    note: 'Données vérifiées par le service RH interne.',
  },
  {
    id: '4',
    salarie: {
      nom: 'Lopez',
      prenom: 'Carlos',
      email: 'carlos.lopez@finanssor.fr',
    },
    annee: 2023,
    mois: 'Octobre',
    nbr_jr: 22,
    note: 'Aucune absence non justifiée n’est signalée.',
  },
  {
    id: '5',
    salarie: {
      nom: 'Moreau',
      prenom: 'Sophie',
      email: 'sophie.moreau@finanssor.fr',
    },
    annee: 2023,
    mois: 'Août',
    nbr_jr: 18,
    note: 'Congés validés en début de mois concerné.',
  },
  {
    id: '6',
    salarie: {
      nom: 'Bertrand',
      prenom: 'Luc',
      email: 'luc.bertrand@finanssor.fr',
    },
    annee: 2023,
    mois: 'Juillet',
    nbr_jr: 20,
    note: 'Le salarié a effectué tous ses jours.',
  },
  {
    id: '7',
    salarie: {
      nom: 'Tremblay',
      prenom: 'Chloé',
      email: 'chloe.tremblay@finanssor.fr',
    },
    annee: 2023,
    mois: 'Décembre',
    nbr_jr: 19,
    note: 'Période marquée par des congés partiels déclarés.',
  },
  {
    id: '8',
    salarie: {
      nom: 'Lemoine',
      prenom: 'Antoine',
      email: 'antoine.lemoine@finanssor.fr',
    },
    annee: 2023,
    mois: 'Juin',
    nbr_jr: 22,
    note: 'Présence totale sans aucun jour d’absence noté.',
  },
  {
    id: '9',
    salarie: {
      nom: 'Fernandez',
      prenom: 'Laura',
      email: 'laura.fernandez@finanssor.fr',
    },
    annee: 2023,
    mois: 'Mai',
    nbr_jr: 21,
    note: 'Absence partielle justifiée par arrêt maladie court.',
  },
  {
    id: '10',
    salarie: { nom: 'Petit', prenom: 'Hugo', email: 'hugo.petit@finanssor.fr' },
    annee: 2023,
    mois: 'Avril',
    nbr_jr: 20,
    note: 'Aucun incident signalé pendant cette période travaillée.',
  },
  {
    id: '11',
    salarie: {
      nom: 'Richard',
      prenom: 'Camille',
      email: 'camille.richard@finanssor.fr',
    },
    annee: 2023,
    mois: 'Mars',
    nbr_jr: 21,
    note: 'Données saisies automatiquement par le logiciel interne.',
  },
  {
    id: '12',
    salarie: {
      nom: 'Blanc',
      prenom: 'Nathan',
      email: 'nathan.blanc@finanssor.fr',
    },
    annee: 2023,
    mois: 'Février',
    nbr_jr: 19,
    note: 'Présence confirmée via les feuilles de pointage RH.',
  },
  {
    id: '13',
    salarie: {
      nom: 'Henry',
      prenom: 'Julie',
      email: 'julie.henry@finanssor.fr',
    },
    annee: 2022,
    mois: 'Décembre',
    nbr_jr: 20,
    note: 'Congés de fin d’année pris en compte également.',
  },
  {
    id: '14',
    salarie: {
      nom: 'Dubois',
      prenom: 'Mathieu',
      email: 'mathieu.dubois@finanssor.fr',
    },
    annee: 2022,
    mois: 'Novembre',
    nbr_jr: 21,
    note: 'Participation complète aux journées obligatoires notée.',
  },
  {
    id: '15',
    salarie: {
      nom: 'Leroux',
      prenom: 'Emma',
      email: 'emma.leroux@finanssor.fr',
    },
    annee: 2022,
    mois: 'Octobre',
    nbr_jr: 22,
    note: 'Tous les jours travaillés ont été validés manuellement.',
  },
  {
    id: '16',
    salarie: { nom: 'Fabre', prenom: 'Axel', email: 'axel.fabre@finanssor.fr' },
    annee: 2022,
    mois: 'Septembre',
    nbr_jr: 20,
    note: 'Aucune anomalie détectée dans le relevé du mois.',
  },
  {
    id: '17',
    salarie: {
      nom: 'Noël',
      prenom: 'Marine',
      email: 'marine.noel@finanssor.fr',
    },
    annee: 2022,
    mois: 'Août',
    nbr_jr: 18,
    note: 'Plusieurs jours fériés ont impacté le nombre total.',
  },
  {
    id: '18',
    salarie: {
      nom: 'Benoit',
      prenom: 'Thomas',
      email: 'thomas.benoit@finanssor.fr',
    },
    annee: 2022,
    mois: 'Juillet',
    nbr_jr: 20,
    note: 'L’activité a été normale tout au long du mois.',
  },
  {
    id: '19',
    salarie: { nom: 'Roux', prenom: 'Clara', email: 'clara.roux@finanssor.fr' },
    annee: 2022,
    mois: 'Juin',
    nbr_jr: 21,
    note: 'Les justificatifs d’absence ont bien été déposés.',
  },
  {
    id: '20',
    salarie: {
      nom: 'Girard',
      prenom: 'Louis',
      email: 'louis.girard@finanssor.fr',
    },
    annee: 2022,
    mois: 'Mai',
    nbr_jr: 22,
    note: 'Aucune absence injustifiée enregistrée durant ce mois.',
  },
]
