import type { ICoffreFort } from './CoffreFortTable'

export const data: ICoffreFort[] = [
  {
    id: '1',
    type: 'Bulletin de paie',
    annee: 2024,
    mois: 'Août',
    note: 'Salaire conforme avec les heures prévues.',
  },
  {
    id: '2',
    type: 'Attestation employeur',
    annee: 2023,
    mois: 'Septembre',
    note: 'Fournie pour demande de logement social récemment.',
  },
  {
    id: '3',
    type: 'Contrat de travail',
    annee: 2023,
    mois: 'Novembre',
    note: 'Contrat signé après période d essai validée.',
  },
  {
    id: '4',
    type: 'Relevé d heures',
    annee: 2023,
    mois: 'Octobre',
    note: 'Heures supplémentaires validées par le manager direct.',
  },
  {
    id: '5',
    type: 'Fiche de poste',
    annee: 2023,
    mois: 'Août',
    note: 'Description complète du poste actuel reçue.',
  },
  {
    id: '6',
    type: 'Bulletin de paie',
    annee: 2023,
    mois: 'Juillet',
    note: 'Contient le bonus de performance trimestriel atteint.',
  },
  {
    id: '7',
    type: 'Contrat de travail',
    annee: 2023,
    mois: 'Décembre',
    note: 'Nouvelle affectation précisée dans le contrat signé.',
  },
  {
    id: '8',
    type: 'Attestation employeur',
    annee: 2023,
    mois: 'Juin',
    note: 'Utilisée pour ouverture de compte bancaire professionnel.',
  },
  {
    id: '9',
    type: 'Relevé d heures',
    annee: 2023,
    mois: 'Mai',
    note: 'Inclut les horaires du projet spécial migration.',
  },
  {
    id: '10',
    type: 'Bulletin de paie',
    annee: 2023,
    mois: 'Avril',
    note: 'Ajustement du prélèvement à la source appliqué correctement.',
  },
  {
    id: '11',
    type: 'Fiche de poste',
    annee: 2023,
    mois: 'Mars',
    note: 'Détails mis à jour selon nouvelles missions données.',
  },
  {
    id: '12',
    type: 'Bulletin de paie',
    annee: 2023,
    mois: 'Février',
    note: 'Montant versé égal au net à payer.',
  },
  {
    id: '13',
    type: 'Attestation employeur',
    annee: 2022,
    mois: 'Décembre',
    note: 'Demandée pour validation de l assurance chômage personnelle.',
  },
  {
    id: '14',
    type: 'Contrat de travail',
    annee: 2022,
    mois: 'Novembre',
    note: 'Ancien contrat pour poste précédent en mission courte.',
  },
  {
    id: '15',
    type: 'Relevé d heures',
    annee: 2022,
    mois: 'Octobre',
    note: 'Contient une erreur de cumul d heures mensuelles.',
  },
  {
    id: '16',
    type: 'Bulletin de paie',
    annee: 2022,
    mois: 'Septembre',
    note: 'Dernier bulletin avant changement de poste en interne.',
  },
  {
    id: '17',
    type: 'Fiche de poste',
    annee: 2022,
    mois: 'Août',
    note: 'Fiche initiale du poste avant réorganisation complète.',
  },
  {
    id: '18',
    type: 'Attestation employeur',
    annee: 2022,
    mois: 'Juillet',
    note: 'Utilisée dans le cadre d un dossier CAF récent.',
  },
  {
    id: '19',
    type: 'Contrat de travail',
    annee: 2022,
    mois: 'Juin',
    note: 'Signé au moment de l intégration officielle.',
  },
  {
    id: '20',
    type: 'Relevé d heures',
    annee: 2022,
    mois: 'Mai',
    note: 'Vérifié et signé par l équipe de supervision RH.',
  },
]
