import type { ICoffreFort } from './CoffreFortTable'

export const data: ICoffreFort[] = [
  {
    id: '1',
    salarie: {
      nom: 'Durand',
      prenom: 'Alice',
      email: 'alice.durand@finanssor.fr',
    },
    type: 'Bulletin de paie',
    annee: 2024,
    mois: 'Août',
    note: 'Salaire conforme avec les heures prévues.',
  },
  {
    id: '2',
    salarie: {
      nom: 'Martin',
      prenom: 'Jean',
      email: 'jean.martin@finanssor.fr',
    },
    type: 'Attestation employeur',
    annee: 2023,
    mois: 'Septembre',
    note: 'Fournie pour demande de logement social récemment.',
  },
  {
    id: '3',
    salarie: {
      nom: 'Nguyen',
      prenom: 'Linh',
      email: 'linh.nguyen@finanssor.fr',
    },
    type: 'Contrat de travail',
    annee: 2023,
    mois: 'Novembre',
    note: 'Contrat signé après période d essai validée.',
  },
  {
    id: '4',
    salarie: {
      nom: 'Lopez',
      prenom: 'Carlos',
      email: 'carlos.lopez@finanssor.fr',
    },
    type: 'Relevé d heures',
    annee: 2023,
    mois: 'Octobre',
    note: 'Heures supplémentaires validées par le manager direct.',
  },
  {
    id: '5',
    salarie: {
      nom: 'Moreau',
      prenom: 'Sophie',
      email: 'sophie.moreau@finanssor.fr',
    },
    type: 'Fiche de poste',
    annee: 2023,
    mois: 'Août',
    note: 'Description complète du poste actuel reçue.',
  },
  {
    id: '6',
    salarie: {
      nom: 'Bertrand',
      prenom: 'Luc',
      email: 'luc.bertrand@finanssor.fr',
    },
    type: 'Bulletin de paie',
    annee: 2023,
    mois: 'Juillet',
    note: 'Contient le bonus de performance trimestriel atteint.',
  },
  {
    id: '7',
    salarie: {
      nom: 'Tremblay',
      prenom: 'Chloé',
      email: 'chloe.tremblay@finanssor.fr',
    },
    type: 'Contrat de travail',
    annee: 2023,
    mois: 'Décembre',
    note: 'Nouvelle affectation précisée dans le contrat signé.',
  },
  {
    id: '8',
    salarie: {
      nom: 'Lemoine',
      prenom: 'Antoine',
      email: 'antoine.lemoine@finanssor.fr',
    },
    type: 'Attestation employeur',
    annee: 2023,
    mois: 'Juin',
    note: 'Utilisée pour ouverture de compte bancaire professionnel.',
  },
  {
    id: '9',
    salarie: {
      nom: 'Fernandez',
      prenom: 'Laura',
      email: 'laura.fernandez@finanssor.fr',
    },
    type: 'Relevé d heures',
    annee: 2023,
    mois: 'Mai',
    note: 'Inclut les horaires du projet spécial migration.',
  },
  {
    id: '10',
    salarie: { nom: 'Petit', prenom: 'Hugo', email: 'hugo.petit@finanssor.fr' },
    type: 'Bulletin de paie',
    annee: 2023,
    mois: 'Avril',
    note: 'Ajustement du prélèvement à la source appliqué correctement.',
  },
  {
    id: '11',
    salarie: {
      nom: 'Richard',
      prenom: 'Camille',
      email: 'camille.richard@finanssor.fr',
    },
    type: 'Fiche de poste',
    annee: 2023,
    mois: 'Mars',
    note: 'Détails mis à jour selon nouvelles missions données.',
  },
  {
    id: '12',
    salarie: {
      nom: 'Blanc',
      prenom: 'Nathan',
      email: 'nathan.blanc@finanssor.fr',
    },
    type: 'Bulletin de paie',
    annee: 2023,
    mois: 'Février',
    note: 'Montant versé égal au net à payer.',
  },
  {
    id: '13',
    salarie: {
      nom: 'Henry',
      prenom: 'Julie',
      email: 'julie.henry@finanssor.fr',
    },
    type: 'Attestation employeur',
    annee: 2022,
    mois: 'Décembre',
    note: 'Demandée pour validation de l assurance chômage personnelle.',
  },
  {
    id: '14',
    salarie: {
      nom: 'Dubois',
      prenom: 'Mathieu',
      email: 'mathieu.dubois@finanssor.fr',
    },
    type: 'Contrat de travail',
    annee: 2022,
    mois: 'Novembre',
    note: 'Ancien contrat pour poste précédent en mission courte.',
  },
  {
    id: '15',
    salarie: {
      nom: 'Leroux',
      prenom: 'Emma',
      email: 'emma.leroux@finanssor.fr',
    },
    type: 'Relevé d heures',
    annee: 2022,
    mois: 'Octobre',
    note: 'Contient une erreur de cumul d heures mensuelles.',
  },
  {
    id: '16',
    salarie: { nom: 'Fabre', prenom: 'Axel', email: 'axel.fabre@finanssor.fr' },
    type: 'Bulletin de paie',
    annee: 2022,
    mois: 'Septembre',
    note: 'Dernier bulletin avant changement de poste en interne.',
  },
  {
    id: '17',
    salarie: {
      nom: 'Noël',
      prenom: 'Marine',
      email: 'marine.noel@finanssor.fr',
    },
    type: 'Fiche de poste',
    annee: 2022,
    mois: 'Août',
    note: 'Fiche initiale du poste avant réorganisation complète.',
  },
  {
    id: '18',
    salarie: {
      nom: 'Benoit',
      prenom: 'Thomas',
      email: 'thomas.benoit@finanssor.fr',
    },
    type: 'Attestation employeur',
    annee: 2022,
    mois: 'Juillet',
    note: 'Utilisée dans le cadre d un dossier CAF récent.',
  },
  {
    id: '19',
    salarie: { nom: 'Roux', prenom: 'Clara', email: 'clara.roux@finanssor.fr' },
    type: 'Contrat de travail',
    annee: 2022,
    mois: 'Juin',
    note: 'Signé au moment de l intégration officielle.',
  },
  {
    id: '20',
    salarie: {
      nom: 'Girard',
      prenom: 'Louis',
      email: 'louis.girard@finanssor.fr',
    },
    type: 'Relevé d heures',
    annee: 2022,
    mois: 'Mai',
    note: 'Vérifié et signé par l équipe de supervision RH.',
  },
]
