export const countriesData = [
  {
    label: 'AFGHANISTAN',
    value: '1',
  },
  { label: 'ALBANIA', value: '2' },
  { label: 'ALGERIA', value: '3' },
  { label: 'AMERICAN SAMOA', value: '4' },
  { label: 'ANDORRA', value: '5' },
  { label: 'ANGOLA', value: '6' },
  { label: 'ANGUILLA', value: '7' },
  { label: 'ANTARCTICA', value: '8' },
  { label: 'ANTIGUA AND BARBUDA', value: '9' },
  { label: 'ARGENTINA', value: '10' },
  { label: 'ARMENIA', value: '11' },
  { label: 'ARUBA', value: '12' },
  { label: 'AUSTRALIA', value: '13' },
  { label: 'AUSTRIA', value: '14' },
  { label: 'AZERBAIJAN', value: '15' },
  { label: 'BAHAMAS', value: '16' },
  { label: 'BAHRAIN', value: '17' },
  { label: 'BANGLADESH', value: '18' },
  { label: 'BARBADOS', value: '19' },
  { label: 'BELARUS', value: '20' },
  { label: 'BELGIUM', value: '21' },
  { label: 'BELIZE', value: '22' },
  { label: 'BENIN', value: '23' },
  { label: 'BERMUDA', value: '24' },
  { label: 'BHUTAN', value: '25' },
  { label: 'BOLIVIA', value: '26' },
  { label: 'BOSNIA AND HERZEGOVINA', value: '27' },
  { label: 'BOTSWANA', value: '28' },
  { label: 'BOUVET ISLAND', value: '29' },
  { label: 'BRAZIL', value: '30' },
  { label: 'BRITISH INDIAN OCEAN TERRITORY', value: '31' },
  { label: 'BRUNEI DARUSSALAM', value: '32' },
  { label: 'BULGARIA', value: '33' },
  { label: 'BURKINA FASO', value: '34' },
  { label: 'BURUNDI', value: '35' },
  { label: 'CAMBODIA', value: '36' },
  { label: 'CAMEROON', value: '37' },
  { label: 'CANADA', value: '38' },
  { label: 'CAPE VERDE', value: '39' },
  { label: 'CAYMAN ISLANDS', value: '40' },
  { label: 'CENTRAL AFRICAN REPUBLIC', value: '41' },
  { label: 'CHAD', value: '42' },
  { label: 'CHILE', value: '43' },
  { label: 'CHINA', value: '44' },
  { label: 'CHRISTMAS ISLAND', value: '45' },
  { label: 'COCOS (KEELING) ISLANDS', value: '46' },
  { label: 'COLOMBIA', value: '47' },
  { label: 'COMOROS', value: '48' },
  { label: 'CONGO', value: '49' },
  { label: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', value: '50' },
  { label: 'COOK ISLANDS', value: '51' },
  { label: 'COSTA RICA', value: '52' },
  { label: "COTE D'IVOIRE", value: '53' },
  { label: 'CROATIA', value: '54' },
  { label: 'CUBA', value: '55' },
  { label: 'CYPRUS', value: '56' },
  { label: 'CZECH REPUBLIC', value: '57' },
  { label: 'DENMARK', value: '58' },
  { label: 'DJIBOUTI', value: '59' },
  { label: 'DOMINICA', value: '60' },
  { label: 'DOMINICAN REPUBLIC', value: '61' },
  { label: 'ECUADOR', value: '62' },
  { label: 'EGYPT', value: '63' },
  { label: 'EL SALVADOR', value: '64' },
  { label: 'EQUATORIAL GUINEA', value: '65' },
  { label: 'ERITREA', value: '66' },
  { label: 'ESTONIA', value: '67' },
  { label: 'ETHIOPIA', value: '68' },
  { label: 'FALKLAND ISLANDS (MALVINAS)', value: '69' },
  { label: 'FAROE ISLANDS', value: '70' },
  { label: 'FIJI', value: '71' },
  { label: 'FINLAND', value: '72' },
  { label: 'FRANCE', value: '73' },
  { label: 'FRENCH GUIANA', value: '74' },
  { label: 'FRENCH POLYNESIA', value: '75' },
  { label: 'FRENCH SOUTHERN TERRITORIES', value: '76' },
  { label: 'GABON', value: '77' },
  { label: 'GAMBIA', value: '78' },
  { label: 'GEORGIA', value: '79' },
  { label: 'GERMANY', value: '80' },
  { label: 'GHANA', value: '81' },
  { label: 'GIBRALTAR', value: '82' },
  { label: 'GREECE', value: '83' },
  { label: 'GREENLAND', value: '84' },
  { label: 'GRENADA', value: '85' },
  { label: 'GUADELOUPE', value: '86' },
  { label: 'GUAM', value: '87' },
  { label: 'GUATEMALA', value: '88' },
  { label: 'GUINEA', value: '89' },
  { label: 'GUINEA-BISSAU', value: '90' },
  { label: 'GUYANA', value: '91' },
  { label: 'HAITI', value: '92' },
  { label: 'HEARD ISLAND AND MCDONALD ISLANDS', value: '93' },
  { label: 'HOLY SEE (VATICAN CITY STATE)', value: '94' },
  { label: 'HONDURAS', value: '95' },
  { label: 'HONG KONG', value: '96' },
  { label: 'HUNGARY', value: '97' },
  { label: 'ICELAND', value: '98' },
  { label: 'INDIA', value: '99' },
  { label: 'INDONESIA', value: '100' },
  { label: 'IRAN, ISLAMIC REPUBLIC OF', value: '101' },
  { label: 'IRAQ', value: '102' },
  { label: 'IRELAND', value: '103' },
  { label: 'ISRAEL', value: '104' },
  { label: 'ITALY', value: '105' },
  { label: 'JAMAICA', value: '106' },
  { label: 'JAPAN', value: '107' },
  { label: 'JORDAN', value: '108' },
  { label: 'KAZAKHSTAN', value: '109' },
  { label: 'KENYA', value: '110' },
  { label: 'KIRIBATI', value: '111' },
  { label: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", value: '112' },
  { label: 'KOREA, REPUBLIC OF', value: '113' },
  { label: 'KUWAIT', value: '114' },
  { label: 'KYRGYZSTAN', value: '115' },
  { label: "LAO PEOPLE'S DEMOCRATIC REPUBLIC", value: '116' },
  { label: 'LATVIA', value: '117' },
  { label: 'LEBANON', value: '118' },
  { label: 'LESOTHO', value: '119' },
  { label: 'LIBERIA', value: '120' },
  { label: 'LIBYAN ARAB JAMAHIRIYA', value: '121' },
  { label: 'LIECHTENSTEIN', value: '122' },
  { label: 'LITHUANIA', value: '123' },
  { label: 'LUXEMBOURG', value: '124' },
  { label: 'MACAO', value: '125' },
  { label: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', value: '126' },
  { label: 'MADAGASCAR', value: '127' },
  { label: 'MALAWI', value: '128' },
  { label: 'MALAYSIA', value: '129' },
  { label: 'MALDIVES', value: '130' },
  { label: 'MALI', value: '131' },
  { label: 'MALTA', value: '132' },
  { label: 'MARSHALL ISLANDS', value: '133' },
  { label: 'MARTINIQUE', value: '134' },
  { label: 'MAURITANIA', value: '135' },
  { label: 'MAURITIUS', value: '136' },
  { label: 'MAYOTTE', value: '137' },
  { label: 'MEXICO', value: '138' },
  { label: 'MICRONESIA, FEDERATED STATES OF', value: '139' },
  { label: 'MOLDOVA, REPUBLIC OF', value: '140' },
  { label: 'MONACO', value: '141' },
  { label: 'MONGOLIA', value: '142' },
  { label: 'MONTSERRAT', value: '143' },
  { label: 'MOROCCO', value: '144' },
  { label: 'MOZAMBIQUE', value: '145' },
  { label: 'MYANMAR', value: '146' },
  { label: 'NAMIBIA', value: '147' },
  { label: 'NAURU', value: '148' },
  { label: 'NEPAL', value: '149' },
  { label: 'NETHERLANDS', value: '150' },
  { label: 'NETHERLANDS ANTILLES', value: '151' },
  { label: 'NEW CALEDONIA', value: '152' },
  { label: 'NEW ZEALAND', value: '153' },
  { label: 'NICARAGUA', value: '154' },
  { label: 'NIGER', value: '155' },
  { label: 'NIGERIA', value: '156' },
  { label: 'NIUE', value: '157' },
  { label: 'NORFOLK ISLAND', value: '158' },
  { label: 'NORTHERN MARIANA ISLANDS', value: '159' },
  { label: 'NORWAY', value: '160' },
  { label: 'OMAN', value: '161' },
  { label: 'PAKISTAN', value: '162' },
  { label: 'PALAU', value: '163' },
  { label: 'PALESTINIAN TERRITORY, OCCUPIED', value: '164' },
  { label: 'PANAMA', value: '165' },
  { label: 'PAPUA NEW GUINEA', value: '166' },
  { label: 'PARAGUAY', value: '167' },
  { label: 'PERU', value: '168' },
  { label: 'PHILIPPINES', value: '169' },
  { label: 'PITCAIRN', value: '170' },
  { label: 'POLAND', value: '171' },
  { label: 'PORTUGAL', value: '172' },
  { label: 'PUERTO RICO', value: '173' },
  { label: 'QATAR', value: '174' },
  { label: 'REUNION', value: '175' },
  { label: 'ROMANIA', value: '176' },
  { label: 'RUSSIAN FEDERATION', value: '177' },
  { label: 'RWANDA', value: '178' },
  { label: 'SAINT HELENA', value: '179' },
  { label: 'SAINT KITTS AND NEVIS', value: '180' },
  { label: 'SAINT LUCIA', value: '181' },
  { label: 'SAINT PIERRE AND MIQUELON', value: '182' },
  { label: 'SAINT VINCENT AND THE GRENADINES', value: '183' },
  { label: 'SAMOA', value: '184' },
  { label: 'SAN MARINO', value: '185' },
  { label: 'SAO TOME AND PRINCIPE', value: '186' },
  { label: 'SAUDI ARABIA', value: '187' },
  { label: 'SENEGAL', value: '188' },
  { label: 'SERBIA AND MONTENEGRO', value: '189' },
  { label: 'SEYCHELLES', value: '190' },
  { label: 'SIERRA LEONE', value: '191' },
  { label: 'SINGAPORE', value: '192' },
  { label: 'SLOVAKIA', value: '193' },
  { label: 'SLOVENIA', value: '194' },
  { label: 'SOLOMON ISLANDS', value: '195' },
  { label: 'SOMALIA', value: '196' },
  { label: 'SOUTH AFRICA', value: '197' },
  { label: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', value: '198' },
  { label: 'SPAIN', value: '199' },
  { label: 'SRI LANKA', value: '200' },
  { label: 'SUDAN', value: '201' },
  { label: 'SURIlabel', value: '202' },
  { label: 'SVALBARD AND JAN MAYEN', value: '203' },
  { label: 'SWAZILAND', value: '204' },
  { label: 'SWEDEN', value: '205' },
  { label: 'SWITZERLAND', value: '206' },
  { label: 'SYRIAN ARAB REPUBLIC', value: '207' },
  { label: 'TAIWAN, PROVINCE OF CHINA', value: '208' },
  { label: 'TAJIKISTAN', value: '209' },
  { label: 'TANZANIA, UNITED REPUBLIC OF', value: '210' },
  { label: 'THAILAND', value: '211' },
  { label: 'TIMOR-LESTE', value: '212' },
  { label: 'TOGO', value: '213' },
  { label: 'TOKELAU', value: '214' },
  { label: 'TONGA', value: '215' },
  { label: 'TRINvalueAD AND TOBAGO', value: '216' },
  { label: 'TUNISIA', value: '217' },
  { label: 'TURKEY', value: '218' },
  { label: 'TURKMENISTAN', value: '219' },
  { label: 'TURKS AND CAICOS ISLANDS', value: '220' },
  { label: 'TUVALU', value: '221' },
  { label: 'UGANDA', value: '222' },
  { label: 'UKRAINE', value: '223' },
  { label: 'UNITED ARAB EMIRATES', value: '224' },
  { label: 'UNITED KINGDOM', value: '225' },
  { label: 'UNITED STATES', value: '226' },
  { label: 'UNITED STATES MINOR OUTLYING ISLANDS', value: '227' },
  { label: 'URUGUAY', value: '228' },
  { label: 'UZBEKISTAN', value: '229' },
  { label: 'VANUATU', value: '230' },
  { label: 'VENEZUELA', value: '231' },
  { label: 'VIET NAM', value: '232' },
  { label: 'VIRGIN ISLANDS, BRITISH', value: '233' },
  { label: 'VIRGIN ISLANDS, U.S.', value: '234' },
  { label: 'WALLIS AND FUTUNA', value: '235' },
  { label: 'WESTERN SAHARA', value: '236' },
  { label: 'YEMEN', value: '237' },
  { label: 'ZAMBIA', value: '238' },
  { label: 'ZIMBABWE', value: '239' },
  { label: 'SERBIA', value: '240' },
  { label: 'ASIA PACIFIC REGION', value: '241' },
  { label: 'MONTENEGRO', value: '242' },
  { label: 'ALAND ISLANDS', value: '243' },
  { label: 'BONAIRE, SINT EUSTATIUS AND SABA', value: '244' },
  { label: 'CURACAO', value: '245' },
  { label: 'GUERNSEY', value: '246' },
  { label: 'ISLE OF MAN', value: '247' },
  { label: 'JERSEY', value: '248' },
  { label: 'KOSOVO', value: '249' },
  { label: 'SAINT BARTHELEMY', value: '250' },
  { label: 'SAINT MARTIN', value: '251' },
  { label: 'SINT MAARTEN', value: '252' },
  { label: 'SOUTH SUDAN', value: '253' },
]
