export const countriesData = [
  { label: 'AFGHANISTAN', value: '1' },
  { label: 'ALBANIE', value: '2' },
  { label: 'ALGÉRIE', value: '3' },
  { label: 'ANDORRE', value: '4' },
  { label: 'ANGOLA', value: '5' },
  { label: 'ANTIGUA-ET-BARBUDA', value: '6' },
  { label: 'ARGENTINE', value: '7' },
  { label: 'ARMÉNIE', value: '8' },
  { label: 'AUSTRALIE', value: '9' },
  { label: 'AUTRICHE', value: '10' },
  { label: 'AZERBAÏDJAN', value: '11' },
  { label: 'BAHAMAS', value: '12' },
  { label: 'BAHREÏN', value: '13' },
  { label: 'BANGLADESH', value: '14' },
  { label: 'BARBADE', value: '15' },
  { label: 'BELGIQUE', value: '16' },
  { label: 'BELIZE', value: '17' },
  { label: 'BÉNIN', value: '18' },
  { label: 'BHOUTAN', value: '19' },
  { label: 'BOLIVIE', value: '20' },
  { label: 'BOSNIE-HERZÉGOVINE', value: '21' },
  { label: 'BOTSWANA', value: '22' },
  { label: 'BRÉSIL', value: '23' },
  { label: 'BRUNÉI', value: '24' },
  { label: 'BULGARIE', value: '25' },
  { label: 'BURKINA FASO', value: '26' },
  { label: 'BURUNDI', value: '27' },
  { label: 'CAMBODGE', value: '28' },
  { label: 'CAMEROUN', value: '29' },
  { label: 'CANADA', value: '30' },
  { label: 'CAP-VERT', value: '31' },
  { label: 'RÉPUBLIQUE CENTRAFRICAINE', value: '32' },
  { label: 'TCHAD', value: '33' },
  { label: 'CHILI', value: '34' },
  { label: 'CHINE', value: '35' },
  { label: 'COLOMBIE', value: '36' },
  { label: 'COMORES', value: '37' },
  { label: 'CONGO', value: '38' },
  { label: 'RÉPUBLIQUE DÉMOCRATIQUE DU CONGO', value: '39' },
  { label: 'COSTA RICA', value: '40' },
  { label: 'CÔTE D’IVOIRE', value: '41' },
  { label: 'CROATIE', value: '42' },
  { label: 'CUBA', value: '43' },
  { label: 'CHYPRE', value: '44' },
  { label: 'RÉPUBLIQUE TCHÈQUE', value: '45' },
  { label: 'DANEMARK', value: '46' },
  { label: 'DJIBOUTI', value: '47' },
  { label: 'DOMINIQUE', value: '48' },
  { label: 'RÉPUBLIQUE DOMINICAINE', value: '49' },
  { label: 'ÉQUATEUR', value: '50' },
  { label: 'ÉGYPTE', value: '51' },
  { label: 'EL SALVADOR', value: '52' },
  { label: 'GUINÉE ÉQUATORIALE', value: '53' },
  { label: 'ÉRYTHRÉE', value: '54' },
  { label: 'ESTONIE', value: '55' },
  { label: 'ÉTHIOPIE', value: '56' },
  { label: 'FIDJI', value: '57' },
  { label: 'FINLANDE', value: '58' },
  { label: 'FRANCE', value: '73' },
  { label: 'GABON', value: '60' },
  { label: 'GAMBIE', value: '61' },
  { label: 'GÉORGIE', value: '62' },
  { label: 'ALLEMAGNE', value: '63' },
  { label: 'GHANA', value: '64' },
  { label: 'GRÈCE', value: '65' },
  { label: 'GRENADE', value: '66' },
  { label: 'GUATEMALA', value: '67' },
  { label: 'GUINÉE', value: '68' },
  { label: 'GUINÉE-BISSAU', value: '69' },
  { label: 'GUYANA', value: '70' },
  { label: 'HAÏTI', value: '71' },
  { label: 'HONDURAS', value: '72' },
  { label: 'HONGRIE', value: '59' },
  { label: 'ISLANDE', value: '74' },
  { label: 'INDE', value: '75' },
  { label: 'INDONÉSIE', value: '76' },
  { label: 'IRAN', value: '77' },
  { label: 'IRAK', value: '78' },
  { label: 'IRLANDE', value: '79' },
  { label: 'ITALIE', value: '81' },
  { label: 'JAMAÏQUE', value: '82' },
  { label: 'JAPON', value: '83' },
  { label: 'JORDANIE', value: '84' },
  { label: 'KAZAKHSTAN', value: '85' },
  { label: 'KENYA', value: '86' },
  { label: 'KIRIBATI', value: '87' },
  { label: 'CORÉE DU NORD', value: '88' },
  { label: 'CORÉE DU SUD', value: '89' },
  { label: 'KOWEÏT', value: '90' },
  { label: 'KIRGHIZISTAN', value: '91' },
  { label: 'LAOS', value: '92' },
  { label: 'LETTONIE', value: '93' },
  { label: 'LIBAN', value: '94' },
  { label: 'LIBÉRIA', value: '95' },
  { label: 'LIBYE', value: '96' },
  { label: 'LIECHTENSTEIN', value: '97' },
  { label: 'LITUANIE', value: '98' },
  { label: 'LUXEMBOURG', value: '99' },
  { label: 'MACÉDOINE', value: '100' },
  { label: 'MADAGASCAR', value: '101' },
  { label: 'MALAWI', value: '102' },
  { label: 'MALAISIE', value: '103' },
  { label: 'MALDIVES', value: '104' },
  { label: 'MALI', value: '105' },
  { label: 'MALTE', value: '106' },
  { label: 'ÎLES MARSHALL', value: '107' },
  { label: 'MAURITANIE', value: '108' },
  { label: 'MAURICE', value: '109' },
  { label: 'MEXIQUE', value: '110' },
  { label: 'MICRONÉSIE', value: '111' },
  { label: 'MOLDAVIE', value: '112' },
  { label: 'MONACO', value: '113' },
  { label: 'MONGOLIE', value: '114' },
  { label: 'MONTÉNÉGRO', value: '115' },
  { label: 'MAROC', value: '116' },
  { label: 'MOZAMBIQUE', value: '117' },
  { label: 'NAMIBIE', value: '118' },
  { label: 'NAURU', value: '119' },
  { label: 'NÉPAL', value: '120' },
  { label: 'PAYS-BAS', value: '121' },
  { label: 'NOUVELLE-ZÉLANDE', value: '122' },
  { label: 'NICARAGUA', value: '123' },
  { label: 'NIGER', value: '124' },
  { label: 'NIGÉRIA', value: '125' },
  { label: 'NORVÈGE', value: '126' },
  { label: 'OMAN', value: '127' },
  { label: 'PAKISTAN', value: '128' },
  { label: 'PALAOS', value: '129' },
  { label: 'PANAMA', value: '130' },
  { label: 'PAPOUASIE-NOUVELLE-GUINÉE', value: '131' },
  { label: 'PARAGUAY', value: '132' },
  { label: 'PÉROU', value: '133' },
  { label: 'PHILIPPINES', value: '134' },
  { label: 'POLOGNE', value: '135' },
  { label: 'PORTUGAL', value: '136' },
  { label: 'QATAR', value: '137' },
  { label: 'ROUMANIE', value: '138' },
  { label: 'RUSSIE', value: '139' },
  { label: 'RWANDA', value: '140' },
  { label: 'SAINT-KITTS-ET-NEVIS', value: '141' },
  { label: 'SAINTE-LUCIE', value: '142' },
  { label: 'SAINT-VINCENT-ET-LES-GRENADINES', value: '143' },
  { label: 'SAMOA', value: '144' },
  { label: 'SAINT-MARIN', value: '145' },
  { label: 'ARABIE SAOUDITE', value: '146' },
  { label: 'SÉNÉGAL', value: '147' },
  { label: 'SERBIE', value: '148' },
  { label: 'SEYCHELLES', value: '149' },
  { label: 'SIERRA LEONE', value: '150' },
  { label: 'SINGAPOUR', value: '151' },
  { label: 'SLOVAQUIE', value: '152' },
  { label: 'SLOVÉNIE', value: '153' },
  { label: 'ÎLES SALOMON', value: '154' },
  { label: 'SOMALIE', value: '155' },
  { label: 'AFRIQUE DU SUD', value: '156' },
  { label: 'SUD-SOUDAN', value: '157' },
  { label: 'ESPAGNE', value: '158' },
  { label: 'SRI LANKA', value: '159' },
  { label: 'SOUDAN', value: '160' },
  { label: 'SURINAME', value: '161' },
  { label: 'ESWATINI', value: '162' },
  { label: 'SUÈDE', value: '163' },
  { label: 'SUISSE', value: '164' },
  { label: 'SYRIE', value: '165' },
  { label: 'TAÏWAN', value: '166' },
  { label: 'TADJIKISTAN', value: '167' },
  { label: 'TANZANIE', value: '168' },
  { label: 'THAÏLANDE', value: '169' },
  { label: 'TIMOR-LESTE', value: '170' },
  { label: 'TOGO', value: '171' },
  { label: 'TONGA', value: '172' },
  { label: 'TRINITÉ-ET-TOBAGO', value: '173' },
  { label: 'TUNISIE', value: '174' },
  { label: 'TURQUIE', value: '175' },
  { label: 'TURKMÉNISTAN', value: '176' },
  { label: 'TUVALU', value: '177' },
  { label: 'OUGANDA', value: '178' },
  { label: 'UKRAINE', value: '179' },
  { label: 'ÉMIRATS ARABES UNIS', value: '180' },
  { label: 'ROYAUME-UNI', value: '181' },
  { label: 'ÉTATS-UNIS', value: '182' },
  { label: 'URUGUAY', value: '183' },
  { label: 'OUZBÉKISTAN', value: '184' },
  { label: 'VANUATU', value: '185' },
  { label: 'VATICAN', value: '186' },
  { label: 'VENEZUELA', value: '187' },
  { label: 'VIÊT NAM', value: '188' },
  { label: 'YÉMEN', value: '189' },
  { label: 'ZAMBIE', value: '190' },
  { label: 'ZIMBABWE', value: '191' },
]
