name: Deploy Frontend (Vite)

on:
  push:
    branches: ['main']

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: 'dist/*'
          target: '/home/ubuntu/apps/frontend/'
